# -*- coding: utf-8 -*-
"""DIP_exp2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-lYgaELf_AT0pB2TQptbQeuQzzTG8YeP
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img1 = cv2.imread('boat3.jpg',1)

image = cv2.imread('boat3.jpg',0)

cv2_imshow(img1)

cv2_imshow(image)

# Negative transformation
negative_image = 255 - image

plt.imshow(negative_image, cmap='gray')
plt.title("Negative Image")
plt.axis('off')
plt.show()

#color negative
neg_color_img = 255-img1

plt.imshow(neg_color_img)
plt.title("Negative Image")
plt.axis('off')
plt.show()

# Log transformation
log_image = np.uint8(np.log1p(image))

plt.imshow(log_image, cmap='gray')
plt.title("Log Transformation")
plt.axis('off')
plt.show()

# Define the gamma value (adjust as needed)
gamma = 0.5

# Power law transformation
power_law_image = np.power(image, gamma).clip(0, 255).astype(np.uint8)

plt.imshow(power_law_image, cmap='gray')
plt.title("Power Law Transformation")
plt.axis('off')
plt.show()

flipped_image = cv2.flip(image, 1)

plt.imshow(flipped_image, cmap='gray')
plt.title("Flipped Image")
plt.axis('off')
plt.show()

