# -*- coding: utf-8 -*-
"""DIP_Exp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1vWObVDNYzGWK0eOMY5tkrNd3mz4Qv5
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/cat.jpg",1)

img2 = cv2.imread("/content/cat.jpg",0)

cv2_imshow(img2)

arr = np.array(img2)

arr.shape

np.shape(img2)

np.shape(img)

img2_resize = cv2.resize(img2,(100,100))

cv2_imshow(img2_resize)

img2_rotated = cv2.rotate(img2_resize,cv2.ROTATE_90_CLOCKWISE)

cv2_imshow(img2_rotated)

img2_color = cv2.cvtColor(img2, cv2.COLOR_GRAY2RGB)

cv2_imshow(cv2.resize(img2_color,(200,200)))

img_gray = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

cv2_imshow(cv2.resize(img_gray,(200,200)))

img3 = cv2.imread("/content/boat.jpg",0)

img3 = cv2.resize(img3,(200,200))
img2 = cv2.resize(img2,(200,200))
img3 = cv2.add(img3,img2)
img3_resize = cv2.resize(img3,(200,200))

cv2_imshow(img3_resize)

img_cat = cv2.imread("/content/cat.jpg")
img_boat = cv2.imread("/content/boat.jpg")

img_cat = cv2.resize(img_cat,(500,500))
img_boat = cv2.resize(img_boat,(500,500))

img_new = cv2.add(img_cat,img_boat)
cv2_imshow(img_new)

